# Generated by Django 2.0.4 on 2018-05-20 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0001_initial'),
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Journalism', 'Journalism')], max_length=250)),
                ('secret_key', models.CharField(default=home_app.models.generate_secret_key, max_length=20)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdittion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_app.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='admin_adittions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.UserAdittion'),
        ),
        migrations.AddField(
            model_name='office',
            name='admin_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.ProfileSettings'),
        ),
    ]
