# Generated by Django 2.0.4 on 2018-06-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_auto_20180601_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeworkers',
            name='joined_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.Office'),
        ),
    ]
