# Generated by Django 2.0.4 on 2018-06-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_auto_20180601_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcament',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.Office'),
        ),
    ]
