# Generated by Django 2.0.4 on 2018-05-01 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deks_images/')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WORLD', 'fa fa-globe'), ('METRO', 'Metro'), ('POLITICS', 'Politics'), ('BUSINESS', 'Business'), ('TECH', 'Tech'), ('SCIENCE', 'Science'), ('OPINION', 'Opinion'), ('HEALTH', 'Health'), ('SPORTS', 'Sports'), ('ARTS', 'Arts'), ('BOOKS', 'Books'), ('STYLE', 'Style'), ('TRAVEL', 'Travel'), ('MAGAZINE', 'Magazine'), ('TABLOID', 'Tabloid')], max_length=50)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
