# Generated by Django 2.0.4 on 2018-05-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk',
            old_name='editor',
            new_name='sub_editor',
        ),
    ]
