# Generated by Django 2.0.4 on 2018-05-02 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0002_auto_20180501_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='category_color',
            field=models.CharField(choices=[('WORLD', '#3498DB'), ('METRO', '#2980B9'), ('POLITICS', '#5D6D7E'), ('BUSINESS', '#2E4053'), ('TECH', '#F4D03F'), ('SCIENCE', '#2ECC71'), ('OPINION', '#9B59B6'), ('HEALTH', '#E74C3C'), ('SPORTS', '#58D68D'), ('ARTS', '#F39C12'), ('BOOKS', '#E67E22'), ('STYLE', '#F5B7B1'), ('TRAVEL', '#BB8FCE'), ('MAGAZINE', '#8E44AD'), ('TABLOID', '#A569BD')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desk',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='desk',
            name='category',
            field=models.CharField(choices=[('WORLD', 'fa fa-globe'), ('METRO', 'fa fa-building'), ('POLITICS', 'fa-flag'), ('BUSINESS', 'fa fa-suitcase'), ('TECH', 'fa fa-code'), ('SCIENCE', 'fa fa-flask'), ('OPINION', 'fa fa-gavel'), ('HEALTH', 'fa fa-heart'), ('SPORTS', 'fa fa-bicycle'), ('ARTS', 'fa fa-paint-brush'), ('BOOKS', 'fa fa-book'), ('STYLE', 'fa fa-eye'), ('TRAVEL', 'fa fa-plane'), ('MAGAZINE', 'fa fa-file'), ('TABLOID', 'fa fa-phone')], max_length=50),
        ),
    ]
