# Generated by Django 2.0.4 on 2018-05-02 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk_app', '0003_auto_20180502_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOINED_DESK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_app.Desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
