# Generated by Django 2.0.4 on 2018-05-02 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk_app', '0004_joined_desk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JOINED_DESK',
            new_name='DeskWorkers',
        ),
        migrations.RenameField(
            model_name='deskworkers',
            old_name='user',
            new_name='worker',
        ),
    ]
