# Generated by Django 2.0.4 on 2018-05-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk_app', '0005_auto_20180502_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('task_completed', models.BooleanField(default=False)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_app.Desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
