# Generated by Django 2.0.4 on 2018-05-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0007_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desk_app.Desk'),
        ),
    ]
