# Generated by Django 2.0.4 on 2018-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0008_auto_20180511_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pushed_to_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='pushed_to_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='pushed_to_review',
            field=models.BooleanField(default=False),
        ),
    ]
