# Generated by Django 2.0.4 on 2018-05-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0009_auto_20180511_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pushed_to_review',
        ),
    ]
