# Generated by Django 2.0.4 on 2018-05-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('desk_app', '0010_remove_article_pushed_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_app.ProfileSettings'),
        ),
    ]
