# Generated by Django 2.0.4 on 2018-06-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_announcament_office'),
        ('desk_app', '0012_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.Office'),
        ),
    ]
