# Generated by Django 2.0.4 on 2018-06-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='name',
        ),
    ]
