# Generated by Django 2.0.4 on 2018-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_profilesettings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
